Repository allure-framework/allure-ruby, pull requests merged in 2020-08, with the labels that each got.

#148 Add debug logging to allure lifecycle
  allure-ruby-commons/README.md
  allure-ruby-commons/lib/allure_ruby_commons/allure_lifecycle.rb
  allure-ruby-commons/lib/allure_ruby_commons/config.rb
  allure-ruby-commons/spec/spec_helper.rb
  allure-ruby-commons/spec/unit/attachment_spec.rb
  allure-ruby-commons/spec/unit/test_fixture_spec.rb
  allure-ruby-commons/spec/unit/test_result_container_spec.rb
  allure-ruby-commons/spec/unit/test_result_spec.rb
  allure-ruby-commons/spec/unit/test_step_spec.rb
Labels: type:new feature

#150 Remove everything from allure-results folder
  allure-ruby-commons/lib/allure_ruby_commons/allure_lifecycle.rb
Labels: type:bug

#151 Remove max nesting limit when creating results
  allure-ruby-commons/lib/allure_ruby_commons/file_writer.rb
  allure-ruby-commons/lib/allure_ruby_commons/model/jsonable.rb
Labels: type:enhancement

#155 [CI] Update cc reporter and remove report id from secrets
  .github/workflows/test.yml
  lib/task_helpers/cc_uploader.rb
Labels: type:enhancement

#154 stop_test_step name fix in logger
  allure-ruby-commons/lib/allure_ruby_commons/allure_lifecycle.rb
Labels: type:bug
