Repository allure-framework/allure-ruby, pull requests merged in 2021-02, with the labels that each got.

#217 Return the result of passed block in run_step method
  allure-ruby-commons/lib/allure-ruby-commons.rb
  allure-ruby-commons/spec/unit/allure_spec.rb
Labels: type:enhancement

#219 Add ability to annotate method definitions as allure steps
  .rubocop.yml
  README.md
  allure-cucumber/README.md
  allure-rspec/README.md
  allure-ruby-commons/README.md
  allure-ruby-commons/lib/allure_ruby_commons/step_annotation.rb
  allure-ruby-commons/spec/unit/step_annotation_spec.rb
Labels: type:new feature

#221 Use method name as step name by default
  allure-ruby-commons/lib/allure_ruby_commons/step_annotation.rb
  allure-ruby-commons/spec/unit/step_annotation_spec.rb
Labels: type:enhancement

#222 Use specific ubuntu version in workflows
  .github/workflows/draft-release.yml
  .github/workflows/release.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
Labels: type:chore

#224 feat: add support for rspec tags
  allure-rspec/lib/allure_rspec/tag_parser.rb
  allure-rspec/spec/unit/formatter_example_started_spec.rb
Labels: type:new feature

#226 Extract rubocop in to separate job
  .github/release-drafter.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: type:chore

#230 Add support for after_step hook
  allure-cucumber/lib/allure_cucumber/formatter.rb
  allure-cucumber/lib/allure_cucumber/models/cucumber_model.rb
  allure-cucumber/spec/cucumber_helper.rb
  allure-cucumber/spec/integration/full_report_spec.rb
  allure-cucumber/spec/unit/formatter_test_step_started_spec.rb
  allure-cucumber/spec/unit/formatter_test_step_stopped_spec.rb
Labels: type:bug

#231 Run rubocop in the same workflow
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: type:chore

#232 RSpec: Add support for epic, feature and story tags
  allure-rspec/README.md
  allure-rspec/lib/allure-rspec.rb
  allure-rspec/lib/allure_rspec/01_utils.rb
  allure-rspec/lib/allure_rspec/metadata_parser.rb
  allure-rspec/lib/allure_rspec/rspec_model.rb
  allure-rspec/lib/allure_rspec/tag_parser.rb
  allure-rspec/spec/integration/full_report_spec.rb
  allure-rspec/spec/unit/formatter_example_started_spec.rb
  allure-ruby-commons/lib/allure_ruby_commons/result_utils.rb
  allure-ruby-commons/spec/unit/result_utils_spec.rb
Labels: type:new feature

#233 Codeclimate action
  .github/workflows/test.yml
  lib/task_helpers/cc_uploader.rb
  lib/tasks/test.rake
Labels: type:chore

#234 Cucumber: Add support for epic, feature and story tags
  allure-cucumber/README.md
  allure-cucumber/lib/allure-cucumber.rb
  allure-cucumber/lib/allure_cucumber/config.rb
  allure-cucumber/lib/allure_cucumber/formatter.rb
  allure-cucumber/lib/allure_cucumber/models/cucumber_model.rb
  allure-cucumber/lib/allure_cucumber/models/metadata_parser.rb
  allure-cucumber/lib/allure_cucumber/models/tag_parser.rb
  allure-cucumber/spec/integration/full_report_spec.rb
  allure-cucumber/spec/unit/formatter_test_case_started_spec.rb
Labels: type:new feature
